sensor:
  - platform: template
    sensors:
      fire_alarm_master_bedroom:
        value_template: >-
          {%- if is_state("sensor.fire_alarm_master_bedroom_alarm_type", "13") %}
            Idle
          {%- elif is_state("sensor.fire_alarm_master_bedroom_alarm_type", "1") %}
            FIRE!
          {%- elif is_state("sensor.fire_alarm_master_bedroom_alarm_type", "2") %}
            Carbon Monoxide!
          {%- elif is_state("sensor.fire_alarm_master_bedroom_alarm_type", "12") %}
            Testing
          {%- else -%}
            Unknown
          {%- endif %}
        friendly_name: Master Bedroom
      fire_alarm_second_bedroom:
        value_template: >-
          {%- if is_state("sensor.fire_alarm_second_bedroom_alarm_type", "13") %}
            Idle
          {%- elif is_state("sensor.fire_alarm_second_bedroom_alarm_type", "1") %}
            FIRE!
          {%- elif is_state("sensor.fire_alarm_second_bedroom_alarm_type", "2") %}
            Carbon Monoxide!
          {%- elif is_state("sensor.fire_alarm_second_bedroom_alarm_type", "12") %}
            Testing
          {% else %}
            Unknown
          {%- endif %}
        friendly_name: Second Bedroom
      fire_alarm_third_bedroom:
        value_template: >-
          {%- if is_state("sensor.fire_alarm_third_bedroom_alarm_type", "13") %}
            Idle
          {%- elif is_state("sensor.fire_alarm_third_bedroom_alarm_type", "1") %}
            FIRE!
          {%- elif is_state("sensor.fire_alarm_third_bedroom_alarm_type", "2") %}
            Carbon Monoxide!
          {%- elif is_state("sensor.fire_alarm_third_bedroom_alarm_type", "12") %}
            Testing
          {% else %}
            Unknown
          {%- endif %}
        friendly_name: Third Bedroom
      fire_alarm_fourth_bedroom:
        value_template: >-
          {%- if is_state("sensor.fire_alarm_fourth_bedroom_alarm_type", "13") %}
            Idle
          {%- elif is_state("sensor.fire_alarm_fourth_bedroom_alarm_type", "1") %}
            FIRE!
          {%- elif is_state("sensor.fire_alarm_fourth_bedroom_alarm_type", "2") %}
            Carbon Monoxide!
          {%- elif is_state("sensor.fire_alarm_fourth_bedroom_alarm_type", "12") %}
            Testing
          {% else %}
            Unknown
          {%- endif %}
        friendly_name: Fourth Bedroom
      fire_alarm_hallway:
        value_template: >-
          {%- if is_state("sensor.fire_alarm_hallway_alarm_type", "13") %}
            Idle
          {%- elif is_state("sensor.fire_alarm_hallway_alarm_type", "1") %}
            FIRE!
          {%- elif is_state("sensor.fire_alarm_hallway_alarm_type", "2") %}
            Carbon Monoxide!
          {%- elif is_state("sensor.fire_alarm_hallway_alarm_type", "12") %}
            Testing
          {% else %}
            Unknown
          {%- endif %}
        friendly_name: Hallway 1
      fire_alarm_hallway_2:
        value_template: >-
          {%- if is_state("sensor.fire_alarm_hallway_2_alarm_type", "13") %}
            Idle
          {%- elif is_state("sensor.fire_alarm_hallway_2_alarm_type", "1") %}
            FIRE!
          {%- elif is_state("sensor.fire_alarm_hallway_2_alarm_type", "2") %}
            Carbon Monoxide!
          {%- elif is_state("sensor.fire_alarm_hallway_2_alarm_type", "12") %}
            Testing
          {% else %}
            Unknown
          {%- endif %}
        friendly_name: Hallway 2
      fire_alarm_hallway_3:
        value_template: >-
          {%- if is_state("sensor.fire_alarm_hallway_3_alarm_type", "13") %}
            Idle
          {%- elif is_state("sensor.fire_alarm_hallway_3_alarm_type", "1") %}
            FIRE!
          {%- elif is_state("sensor.fire_alarm_hallway_3_alarm_type", "2") %}
            Carbon Monoxide!
          {%- elif is_state("sensor.fire_alarm_hallway_3_alarm_type", "12") %}
            Testing
          {% else %}
            Unknown
          {%- endif %}
        friendly_name: Hallway 3
      fire_alarm_dining:
        value_template: >-
          {%- if is_state("sensor.fire_alarm_dining_alarm_type", "13") %}
            Idle
          {%- elif is_state("sensor.fire_alarm_dining_alarm_type", "1") %}
            FIRE!
          {%- elif is_state("sensor.fire_alarm_dining_alarm_type", "2") %}
            Carbon Monoxide!
          {%- elif is_state("sensor.fire_alarm_dining_alarm_type", "12") %}
            Testing
          {% else %}
            Unknown
          {%- endif %}
        friendly_name: Dining Room
      fire_alarm_batteries_master_bedroom:
        value_template: '{{states["zwave"]["fire_alarm_master_bedroom"]["attributes"]["battery_level"]}}'
        friendly_name: Master Bedroom
        unit_of_measurement: '%'
        icon_template: >-
          {%- if ((states["zwave"]["fire_alarm_master_bedroom"]["attributes"]["battery_level"]*0.1)|round)*10|int == 100 -%}
            mdi:battery
          {%- else -%}
            mdi:battery-
            {%- if ((states["zwave"]["fire_alarm_master_bedroom"]["attributes"]["battery_level"]*0.1)|round)*10|int == 70 -%}
              60
            {%- elseif ((states["zwave"]["fire_alarm_master_bedroom"]["attributes"]["battery_level"]*0.1)|round)*10|int == 50 -%}
              40
            {%- else -%}
              outline
            {%- endif -%}
          {%- endif -%}
      fire_alarm_batteries_second_bedroom:
        value_template: '{{states["zwave"]["fire_alarm_second_bedroom"]["attributes"]["battery_level"]}}'
        friendly_name: Second Bedroom
        unit_of_measurement: '%'
        icon_template: >-
          {%- if ((states["zwave"]["fire_alarm_second_bedroom"]["attributes"]["battery_level"]*0.1)|round)*10|int == 100 -%}
            mdi:battery
          {%- else -%}
            mdi:battery-
            {%- if ((states["zwave"]["fire_alarm_second_bedroom"]["attributes"]["battery_level"]*0.1)|round)*10|int == 70 -%}
              60
            {%- elseif ((states["zwave"]["fire_alarm_second_bedroom"]["attributes"]["battery_level"]*0.1)|round)*10|int == 50 -%}
              40
            {%- else -%}
              outline
            {%- endif -%}
          {%- endif -%}
      fire_alarm_batteries_third_bedroom:
        value_template: '{{states["zwave"]["fire_alarm_third_bedroom"]["attributes"]["battery_level"]}}'
        friendly_name: Third Bedroom
        unit_of_measurement: '%'
      fire_alarm_batteries_fourth_bedroom:
        value_template: '{{states["zwave"]["fire_alarm_fourth_bedroom"]["attributes"]["battery_level"]}}'
        friendly_name: Fourth Bedroom
        unit_of_measurement: '%'
      fire_alarm_batteries_hallway:
        value_template: '{{states["zwave"]["fire_alarm_hallway"]["attributes"]["battery_level"]}}'
        friendly_name: Hallway 1
        unit_of_measurement: '%'
      fire_alarm_batteries_hallway_2:
        value_template: '{{states["zwave"]["fire_alarm_hallway_2_2"]["attributes"]["battery_level"]}}'
        friendly_name: Hallway 2
        unit_of_measurement: '%'
      fire_alarm_batteries_hallway_3:
        value_template: '{{states["zwave"]["fire_alarm_hallway_3"]["attributes"]["battery_level"]}}'
        friendly_name: Hallway 3
        unit_of_measurement: '%'
      fire_alarm_batteries_dining:
        value_template: '{{states["zwave"]["fire_alarm_dining"]["attributes"]["battery_level"]}}'
        friendly_name: Dining
        unit_of_measurement: '%'
group:
  fire_alarms:
    name: Fire Alarms
    entities:
      - sensor.fire_alarm_master_bedroom
      - sensor.fire_alarm_second_bedroom
      - sensor.fire_alarm_third_bedroom
      - sensor.fire_alarm_fourth_bedroom
      - sensor.fire_alarm_hallway
      - sensor.fire_alarm_hallway_2
      - sensor.fire_alarm_hallway_3
      - sensor.fire_alarm_dining
  fire_alarm_batteries:
    name: Fire Alarms
    entities:
      - sensor.fire_alarm_batteries_master_bedroom
      - sensor.fire_alarm_batteries_second_bedroom
      - sensor.fire_alarm_batteries_third_bedroom
      - sensor.fire_alarm_batteries_fourth_bedroom
      - sensor.fire_alarm_batteries_hallway
      - sensor.fire_alarm_batteries_hallway_2
      - sensor.fire_alarm_batteries_hallway_3
      - sensor.fire_alarm_batteries_dining
