sensor:
  - platform: template
    sensors:
      fire_alarm_master_bedroom:
        value_template: >-
          {%- if is_state("sensor.fire_alarm_master_bedroom_alarm_type", "13") %}
            Idle
          {%- elif is_state("sensor.fire_alarm_master_bedroom_alarm_type", "1") %}
            FIRE!
          {%- elif is_state("sensor.fire_alarm_master_bedroom_alarm_type", "2") %}
            Carbon Monoxide!
          {%- elif is_state("sensor.fire_alarm_master_bedroom_alarm_type", "12") %}
            Testing
          {% else %}
            Unknown
          {%- endif %}
        friendly_name: Master Bedroom
      fire_alarm_second_bedroom:
        value_template: >-
          {%- if is_state("sensor.fire_alarm_second_bedroom_alarm_type", "13") %}
            Idle
          {%- elif is_state("sensor.fire_alarm_second_bedroom_alarm_type", "1") %}
            FIRE!
          {%- elif is_state("sensor.fire_alarm_second_bedroom_alarm_type", "2") %}
            Carbon Monoxide!
          {%- elif is_state("sensor.fire_alarm_second_bedroom_alarm_type", "12") %}
            Testing
          {% else %}
            Unknown
          {%- endif %}
        friendly_name: Second Bedroom
      fire_alarm_third_bedroom:
        value_template: >-
          {%- if is_state("sensor.fire_alarm_third_bedroom_alarm_type", "13") %}
            Idle
          {%- elif is_state("sensor.fire_alarm_third_bedroom_alarm_type", "1") %}
            FIRE!
          {%- elif is_state("sensor.fire_alarm_third_bedroom_alarm_type", "2") %}
            Carbon Monoxide!
          {%- elif is_state("sensor.fire_alarm_third_bedroom_alarm_type", "12") %}
            Testing
          {% else %}
            Unknown
          {%- endif %}
        friendly_name: Third Bedroom
      fire_alarm_fourth_bedroom:
        value_template: >-
          {%- if is_state("sensor.fire_alarm_fourth_bedroom_alarm_type", "13") %}
            Idle
          {%- elif is_state("sensor.fire_alarm_fourth_bedroom_alarm_type", "1") %}
            FIRE!
          {%- elif is_state("sensor.fire_alarm_fourth_bedroom_alarm_type", "2") %}
            Carbon Monoxide!
          {%- elif is_state("sensor.fire_alarm_fourth_bedroom_alarm_type", "12") %}
            Testing
          {% else %}
            Unknown
          {%- endif %}
        friendly_name: Fourth Bedroom
      fire_alarm_hallway:
        value_template: >-
          {%- if is_state("sensor.fire_alarm_hallway_alarm_type", "13") %}
            Idle
          {%- elif is_state("sensor.fire_alarm_hallway_alarm_type", "1") %}
            FIRE!
          {%- elif is_state("sensor.fire_alarm_hallway_alarm_type", "2") %}
            Carbon Monoxide!
          {%- elif is_state("sensor.fire_alarm_hallway_alarm_type", "12") %}
            Testing
          {% else %}
            Unknown
          {%- endif %}
        friendly_name: Hallway 1
      fire_alarm_hallway_2:
        value_template: >-
          {%- if is_state("sensor.fire_alarm_hallway_alarm_2_type", "13") %}
            Idle
          {%- elif is_state("sensor.fire_alarm_hallway_alarm_2_type", "1") %}
            FIRE!
          {%- elif is_state("sensor.fire_alarm_hallway_alarm_2_type", "2") %}
            Carbon Monoxide!
          {%- elif is_state("sensor.fire_alarm_hallway_alarm_2_type", "12") %}
            Testing
          {% else %}
            Unknown
          {%- endif %}
        friendly_name: Hallway 2
      fire_alarm_hallway_3:
        value_template: >-
          {%- if is_state("sensor.fire_alarm_hallway_alarm_3_type", "13") %}
            Idle
          {%- elif is_state("sensor.fire_alarm_hallway_alarm_3_type", "1") %}
            FIRE!
          {%- elif is_state("sensor.fire_alarm_hallway_alarm_3_type", "2") %}
            Carbon Monoxide!
          {%- elif is_state("sensor.fire_alarm_hallway_alarm_3_type", "12") %}
            Testing
          {% else %}
            Unknown
          {%- endif %}
        friendly_name: Hallway 3
      fire_alarm_dining:
        value_template: >-
          {%- if is_state("sensor.fire_alarm_dining_alarm_type", "13") %}
            Idle
          {%- elif is_state("sensor.fire_alarm_dining_alarm_type", "1") %}
            FIRE!
          {%- elif is_state("sensor.fire_alarm_dining_alarm_type", "2") %}
            Carbon Monoxide!
          {%- elif is_state("sensor.fire_alarm_dining_alarm_type", "12") %}
            Testing
          {% else %}
            Unknown
          {%- endif %}
        friendly_name: Dining Room
