name: Home
latitude: !secret latitude
longitude: !secret longitude
elevation: !secret elevation
unit_system: imperial
time_zone: !secret time_zone
packages: !include_dir_named packages
customize: !include_dir_merge_named customize/
customize_glob:
  sensor.fire_alarm_*:
    custom_ui_state_card: custom-ui
