broker: !secret mqtt_broker
port: !secret mqtt_port
keepalive: 60
username: !secret mqtt_username
password: !secret mqtt_password
protocol: 3.1
certificate: !secret mqtt_certificate
tls_insecure: !secret mqtt_tls
