keypad_front:
  name: Front Door Keypad
  view: yes
  icon: mdi:dialpad
  entities:
    - group.door_keypad_front_1
    - group.door_keypad_front_2
    - group.door_keypad_front_3
    - group.door_keypad_front_4
    - group.door_keypad_front_5
    - group.door_keypad_front_6
    - group.door_keypad_front_7
    - group.door_keypad_front_8
    - group.door_keypad_front_9
    - group.door_keypad_front_10
keypad_rear:
  name: Rear Door Keypad
  view: yes
  icon: mdi:dialpad
  entities:
    - group.door_keypad_rear_1
    - group.door_keypad_rear_2
    - group.door_keypad_rear_3
    - group.door_keypad_rear_4
    - group.door_keypad_rear_5
    - group.door_keypad_rear_6
    - group.door_keypad_rear_7
    - group.door_keypad_rear_8
    - group.door_keypad_rear_9
    - group.door_keypad_rear_10
keypad_garage_side:
  name: Garage Side Door Keypad
  view: yes
  icon: mdi:dialpad
  entities:
    - group.door_keypad_garage_side_1
    - group.door_keypad_garage_side_2
    - group.door_keypad_garage_side_3
    - group.door_keypad_garage_side_4
    - group.door_keypad_garage_side_5
    - group.door_keypad_garage_side_6
    - group.door_keypad_garage_side_7
    - group.door_keypad_garage_side_8
    - group.door_keypad_garage_side_9
    - group.door_keypad_garage_side_10
keypad_4th_bedroom:
  name: 4th Bedroom Door Keypad
  view: yes
  icon: mdi:dialpad
  entities:
    - group.door_keypad_4th_bedroom_1
    - group.door_keypad_4th_bedroom_2
    - group.door_keypad_4th_bedroom_3
    - group.door_keypad_4th_bedroom_4
    - group.door_keypad_4th_bedroom_5
    - group.door_keypad_4th_bedroom_6
    - group.door_keypad_4th_bedroom_7
    - group.door_keypad_4th_bedroom_8
    - group.door_keypad_4th_bedroom_9
    - group.door_keypad_4th_bedroom_10
